version: "3.8"

services:
  # Node.js application container
  node-app:
    build: .
    container_name: linkbio-node-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    # Don't expose port directly - only caddy should be accessible from outside

  # Caddy reverse proxy container with automatic HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: linkbio-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data # Persistent storage for certificates
      - caddy_config:/config # Persistent storage for config
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Persistent volumes for Caddy's SSL certificates and config
volumes:
  caddy_data:
  caddy_config:
